#define COLON 1
#define COMMA 2
#define USER 3
#define ISSUE 4
#define HELP 5
#define ENHANCEMENT 6
#define IDENTIFIER 7
#define INTEGER 8
#define ASSIGN 9
#define OBRACKET 10
#define CBRACKET 11
#define NAME 12